Added scripts to claim reward
pantherfoundation/oshiya pull request #2
Opened 2024-10-07 13:09 UTC by Malysh73

Commit includes a script to generate the signature for ClaimRewardWithSignature script

2024-10-18 09:08 UTC, pycckuu requested changes

2024-10-22 14:29 UTC, Malysh73 commented on sdk/scripts/reward/generateSignature.ts
> +    const message = 'Sign this message to generate a signature';
Added tx hashes to description

2024-10-28 05:07 UTC, pycckuu requested changes
The changes are looking solid! Could you also update the readme as I requested?

2024-10-28 05:07 UTC, pycckuu commented on sdk/scripts/reward/utils.ts
> +) {
define returning type

2024-11-06 06:16 UTC, merged